# Generated by Django 3.2.10 on 2021-12-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_city_country_countrylanguage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiTest',
            fields=[
                ('patent_name', models.CharField(max_length=100)),
                ('patent_num', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('patent_peo', models.CharField(max_length=50)),
                ('up_num', models.CharField(blank=True, max_length=20, null=True)),
                ('open_num', models.CharField(blank=True, max_length=20, null=True)),
                ('text', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'ai_test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patent_Chart',
            fields=[
                ('patent_name', models.CharField(max_length=20)),
                ('patent_num', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('patent_peo', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Patent_Chart',
                'managed': False,
            },
        ),
    ]
